import js from "@eslint/js";
import tseslint from "typescript-eslint";
import { globalIgnores } from "eslint/config";

export default tseslint.config(globalIgnores(["dist"]), {
	files: ["**/*.{ts,tsx,js,jsx,mjs}"],
	extends: [js.configs.recommended, tseslint.configs.recommended],
	languageOptions: {
		ecmaVersion: 2020,
	},
	rules: {
		// TypeScript rules
		"@typescript-eslint/ban-ts-comment": "warn",
		"@typescript-eslint/explicit-function-return-type": [
			"error",
			{
				allowExpressions: true,
			},
		],
		"@typescript-eslint/explicit-member-accessibility": [
			"error",
			{
				accessibility: "no-public",
			},
		],
		"@typescript-eslint/member-ordering": "off",
		"@typescript-eslint/no-explicit-any": "off",
		"@typescript-eslint/no-extraneous-class": "error",
		"@typescript-eslint/no-for-in-array": "error",
		"@typescript-eslint/no-misused-promises": "error",
		"@typescript-eslint/no-require-imports": "error",
		"@typescript-eslint/no-shadow": "error",
		"@typescript-eslint/no-unnecessary-qualifier": "error",
		"@typescript-eslint/no-unnecessary-type-assertion": "error",
		"@typescript-eslint/no-use-before-define": [
			"error",
			{
				functions: false,
			},
		],
		"@typescript-eslint/no-useless-constructor": "error",
		"@typescript-eslint/prefer-for-of": "error",
		"@typescript-eslint/prefer-includes": "error",
		"@typescript-eslint/prefer-regexp-exec": "error",
		"@typescript-eslint/prefer-string-starts-ends-with": "error",
		"@typescript-eslint/promise-function-async": "off",
		"@typescript-eslint/require-await": "error",
		"@typescript-eslint/restrict-plus-operands": "error",
		"@typescript-eslint/switch-exhaustiveness-check": "error",
		"@typescript-eslint/unbound-method": "error",
		"@typescript-eslint/unified-signatures": "error",
		"@typescript-eslint/return-await": "error",

		// Best practices
		"accessor-pairs": "error",
		"array-callback-return": "error",
		"class-methods-use-this": "warn",
		"consistent-this": ["error", "self"],
		curly: ["error", "multi-line", "consistent"],
		"dot-notation": "error",
		eqeqeq: [
			"error",
			"always",
			{
				null: "ignore",
			},
		],
		"max-classes-per-file": "warn",
		"new-cap": "warn",
		"no-array-constructor": "error",
		"no-await-in-loop": "warn",
		"no-bitwise": "warn",
		"no-caller": "error",
		"no-console": "error",
		"no-div-regex": "error",
		"no-dupe-class-members": "off",
		"no-duplicate-imports": [
			"error",
			{
				includeExports: true,
			},
		],
		"no-else-return": [
			"error",
			{
				allowElseIf: false,
			},
		],
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-implicit-coercion": [
			"error",
			{
				boolean: false,
			},
		],
		"no-implied-eval": "error",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "error",
		"no-multi-str": "error",
		"no-negated-condition": "error",
		"no-nested-ternary": "error",
		"no-object-constructor": "error",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-octal-escape": "error",
		"no-plusplus": [
			"error",
			{
				allowForLoopAfterthoughts: true,
			},
		],
		"no-proto": "error",
		"no-return-assign": ["error", "always"],
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-shadow": "off",
		"no-template-curly-in-string": "warn",
		"no-throw-literal": "error",
		"no-undef-init": "error",
		"no-underscore-dangle": [
			"error",
			{
				allowAfterSuper: true,
				allowAfterThis: true,
			},
		],
		"no-unmodified-loop-condition": "error",
		"no-unneeded-ternary": [
			"error",
			{
				defaultAssignment: false,
			},
		],
		"no-unused-expressions": "error",
		"no-use-before-define": "off",
		"no-useless-call": "error",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "off",
		"no-useless-rename": "error",
		"no-useless-return": "error",
		"no-var": "error",
		"no-void": "error",
		"no-warning-comments": "warn",
		"object-shorthand": "error",
		"operator-assignment": "error",
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-numeric-literals": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		"require-atomic-updates": "off",
		"sort-imports": "off",
		strict: ["error", "never"],
		"symbol-description": "error",
		yoda: "error",
	},
});
